export const TOGGLE_SIDENAV = 'TOGGLE_SIDENAV';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const TOGGLE_REGISTER_MODAL = 'TOGGLE_REGISTER_MODAL';
export const TOGGLE_MODAL_AUTH = 'TOGGLE_MODAL_AUTH';
export const TOGGLE_MODAL_FORM = 'TOGGLE_MODAL_FORM';
